pipeline {
    agent {
        kubernetes {
            label 'build-pod'
            defaultContainer 'jnlp'
            yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: k8s-deploy
    image: betabandido/k8s-deploy
    command:
    - cat
    tty: true
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
"""
        }
    }
    stages {
        stage('Scale') {
            steps {
                container('k8s-deploy') {
                    dir('k8s') {
                        sh "./scale.sh"
                    }                        
                }
            }
        }
    }
}
